name: release

on:
  release:
    types:
      - published

jobs:
  release-corss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            targets: ${{ matrix.target }}
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: compile
        run: cross build --release --target=${{ matrix.target }} --features 'jemalloc'
      - name: pack unix binary
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf realm-${{ matrix.target }}.tar.gz realm
      - name: add signature
        run: |
          cd release-${{ matrix.target }}
          sha256sum realm-${{ matrix.target }}.tar.gz > realm-${{ matrix.target }}.sha256
      - name: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-${{ matrix.target }}/*
